# Generated by Django 5.2 on 2025-05-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiLog',
        ),
    ]
